pipelines:
  - name: build_deploy_dev
    stages:
      - include: ci_build
        title: foobar bar!
      - title: Deploy to Development
        steps_parallel:
          - run: sleep 2
          - run: sleep 2
          - title: Schlafen
            steps_serial:
              - title: Schlaf mehr parallel
                steps_parallel:
                  - run: sleep 2
                  - run: sleep 2
              - run: sleep 2
              - run: sleep 2
      - title: Notify
        steps_parallel:
          - title: "Send Mail"
            steps_serial:
              - title: "Prepare Mail"
                run: sleep 2
              - title: "Send Mail"
                run: sleep 2
          - title: "Notify slack"
            run: sleep 2

  - name: build_deploy_prod
    stages:
      - title: Deploy to Production
        steps_parallel:
          - run: sleep 2
          - run: sleep 2
      - title: Notify
        steps_parallel:
          - title: "Send Mail"
            run: sleep 2
          - title: "Notify slack"
            run: sleep 2

  - name: build_deploy_staging
    stages:
      - title: Deploy to Staging
        steps_parallel:
          - run: sleep 2
          - run: sleep 2
          - steps_serial:
            - run: sleep 4
            - run: sleep 2
            - run: sleep 3
      - title: Notify
        steps_parallel:
          - title: "Send Mail"
            run: sleep 2
          - title: "Notify slack"
            run: sleep 2

includes:
  ci_build:
    title: CI Build
    steps_serial:
      - run: sleep 2
      - run: sleep 2
      - steps_parallel:
        - run: sleep 2
        - title: Build Assets
          run: sleep 2
