---
type: Build
stages:
  - name: Stage 1
    steps:
      - name: Step 1.1 4sec
        command: sleep 3

      - name: Step 1.2 2sec
        command: sleep 2

      - name: Step 1.3 1sec
        command: sleep 1

  - name: Stage 2
    execution_type: parallel
    steps:
      - name: Step 2.1 4sec
        command: sleep 4

      - name: Step 2.2 echo
        command: sleep 2

      - name: Step 2.3 5sec
        command: sleep 5

  - name: Stage 3
    steps:
      - name: Step 3.1 echo
        command: sleep 1

      - name: Step 3.2 1sec
        command: sleep 1

  - name: Stage 4
    execution_type: parallel
    steps:
      - name: Step 4.1 2sec
        command: sleep 2

      - name: Step 4.2 1sec
        command: sleep 1
