pipelines:
  - name: Build & Deploy to Development
    ref: development
    stages:
      - include: ci_build
      - name: Deploy to Development
        steps_parallel:
          - run: move ec2 --dev
          - run: move s3 --dev
          - name: Schlafen
            steps_serial:
              - name: Schlaf mehr parallel
                steps_parallel:
                  - run: sleep 1
                  - run: sleep 10
              - run: sleep 3
              - run: sleep 4
      - name: Notify
        steps_parallel:
          - name: "Send Mail"
            steps_serial:
              - name: "Prepare Mail"
                run: "mailprepare foo@bar.com"
              - name: "Send Mail"
                run: "sendmail general"
          - name: "Notify slack"
            run: "slacknotify general"

  - name: Build & Deploy to Production
    ref: master
    stages:
      - name: Deploy to Production
        steps_parallel:
          - run: move ec2 --prod
          - run: move s3 --prod
      - name: Notify
        steps_parallel:
          - name: "Send Mail"
            run: "mailsend prodfoo@bar.com"
          - name: "Notify slack"
            run: "slacknotify general"

stages:
  - id: ci_build
    name: CI Build
    steps_serial:
      - run: docker up
      - run: git merge master
      - steps_parallel:
        - run: mix test
        - name: Build Assets
          run: npm run build
