pipelines:
  - id: build_deploy_dev
    stages:
      - include: ci_build
      - name: Deploy to Development
        steps_parallel:
          - run: sleep 2
          - run: sleep 2
          - name: Schlafen
            steps_serial:
              - name: Schlaf mehr parallel
                steps_parallel:
                  - run: sleep 2
                  - run: sleep 2
              - run: sleep 2
              - run: sleep 2
      - name: Notify
        steps_parallel:
          - name: "Send Mail"
            steps_serial:
              - name: "Prepare Mail"
                run: sleep 2
              - name: "Send Mail"
                run: sleep 2
          - name: "Notify slack"
            run: sleep 2

  - id: build_deploy_prod
    stages:
      - name: Deploy to Production
        steps_parallel:
          - run: sleep 2
          - run: sleep 2
      - name: Notify
        steps_parallel:
          - name: "Send Mail"
            run: sleep 2
          - name: "Notify slack"
            run: sleep 2

stages:
  - id: ci_build
    name: CI Build
    steps_serial:
      - run: sleep 2
      - run: sleep 2
      - steps_parallel:
        - run: sleep 2
        - name: Build Assets
          run: sleep 2
