---
env: default
stages:
  - name: Prepare Environment
    steps:
      - name: Cleanup
        command: rm sth

      - name: Checkout
        command: git clone sth

  - name: Build
    steps:
      - name: install dependencies
        command: npm install

      - name: run unit tests
        command: npm test

      - name: build executable
        command: npm run build

  - name: Transfer
    steps:
      - name: transfer files to aws
        command: mv sth sth2

  - name: Testing
    steps:
      - name: smoke test
        command: smoketest sth
